#
# This file contains configuration flags to customize your site
#
name: "The Trellis Tech Blog"
title: "Trellis"
description: "Open source, technology impact, Nest and Angular."
avatar: https://trellis.org/new_assets/icons/icon-128x128.png
logo: https://trellis.org/new_assets/icons/icon-128x128.png
favicon: https://trellis.org/new_assets/icons/icon-128x128.png
include: ["_pages"]
permalink: /:title/
url: https://tech.trellis.org

# Authors
authors:
  jay:
    name: Jay Bell
    display_name: Jay
    email: jay@trellis.org
    web: https://trellis.org
    twitter: https://twitter.com/jaycooperbell
    avatar: https://pbs.twimg.com/profile_images/1179854396579930112/0wSEx6SJ_400x400.jpg
    description: "CTO and Co-Founder of Trellis.org, Angular GDE and open source contributor."

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Other
markdown: kramdown

# Pagination
paginate: 6
paginate_path: /page:num/

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
